# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "T7iY7/txkep+XT+606iUWRyVHWTtHCk/QXZivlSymJIlZ/KavKJH2+Qzj9OSB6WuR9g4A7TAA2jcSROrXnGoiL8htHTJwCC5hwXh8l5jZAkFSqu9we+5CQfVM+8OYZ83FKXxoxbDgr7NcxOMPwlTcg2l5gKN+x/pknoS4hiJODFDfI8JzLPFpXJtjoY9P6Ob3jV6cKrXYGNlAs7YFF7NMUvYCS0VHFzbqk++uq/Dohrqmh84swvvzFd9CavrpbMTZXg3gJ8DVZoBUOZPhO3sQs3UcwKZKeeCJrAgJW534ywdgYvk7h2Ep1aGYB6/e1a51+Qa0UpV10y8nUjCzN2GxWgDnBGGhpzx7pQQ/R/bUKb+LkFe5yJb/WrRO1tRZZjW34nAICQT0Obnc1l7L43l9ROPTCgkGxWSRI6yX7Zv6CLbYS8Onrf/J4m+89LZBp6hPFAAFETvrIy1fKShnSv6r/Gwpr6vJUIwpPNDGVVa2AXEzLWgNUG2iNvbuAbtsoFieVHLmy5GEO3DRtzKkgpoauRwUustELUu2PFvx+xw0MC4FbdJyDkBRtgZsiAm4oQXgM8THQ+SxQnQmQf2l9rehvglOiT6NoeIv6te3NRDFq0+qNzY24CnMyJWm0mNOn6T8plCiLfnzA/JL899LZZomk1ATkeopyEuU1scSeo0Mi8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
