travis:
  secure:
    BINSTAR_TOKEN: g6t7NCJ4SEFf5vm27fsWCF1Wc8MG9tRQSVuoHi1TGbtMQ3yEs8jyY136mWVLVNfatF8He6I7Y+rS9bN4UBMk7G7knzw1oZvIGgvIQS4ey5MisbobFS4lTZSTB2gxs/EThzaGHov3/viP0oUMYFBudaYBmXEWZrURBh1k+xF4Nyne6bGq0MmCaeR1UfEw6vTTeLASrIfbNLTffi0GRLBmEedotUp1+SZ8YtNeYGLIV4s9cdZ9R2dsPwQOMnioWuCvXjhsyHQ0VE9LJ0YOmIM0nfPQF26SVGz9gGhItpqWNIIYO8VS/bv5hcGgatQHLi78QwV6QDo8g1tpG/3bPi+TFQ2LY5B8w1+aWM7rAo66c36fgB1YfzcSiyUIp9XFWMcWJd2yMDQbjHcI7YuN9Rp0Yr8l4sXwo6mSQuXD7zlgiqmOLO1Jg9Aw9Uc4w0RNtfAcePjA3ezF0nlsgvTR4O+/ttnAmvZSRvloQI/MixhRb8sGdl4EFN7U5d8SwuoVevlNdiHsNZSz5zrwCDojarIjSx6OuWWCg68aN0uTt5IGluvsNePfP/D2OJAMLfHWeW8pbI/hG9uF68HR0bID+5sSsx4D8ekb8hTkxK8GhIGZ7WvkdUQTYYFrrSXpQmBNUSygJtYkS9V5znM3kQgKG/4tXGZH1sX1FtEvbQfBIKILU0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
