travis:
  secure:
    BINSTAR_TOKEN: nLTeAm+3OqDelNiUYFoGrZTqFl3JUZzkVShf6meZ3TnfsTwq1mUsRDgEyxQUYj4Q/RuMOKT6yXMM2aOCGoDw4+ws8XARsl6sLNzrWoThsxTWjOkauUBWmUC2dsOPChDGlsdZzDwJC55dZjq5udRwID/B+YhKpuywtlSVLHvIiQ43cIg6ZFDXBXVTy0vcwQkrOgb9aFZhYk6120wtamHrHRczg0WST/Q2VLL9oXYU3q1zR/lmkAE4vaSvXVn6KQveU+N1N/0iB2fCMiHBvRQZa7c+yJhJKF4rkSCHNgfl3QXN/GEo5rNhpGuCUbmolY2ThF0VMXkBHa15+28QuPIsx2kc4DPec/gu0wEoAwvi72kOacJITW6NDXnax4G7vhNh+L/vrJZt5/PIs7i6ps9gsePJk+vYILECQpWrLcWnqcsfCsCqIaCgKxTF03DSKk6Ly0PPXHg5nvviWZHLjXFouS/DwPBYmzhvblOIjr/VcUmr5GdM1AteTlTeCfz/1k/81H9R2d0YxjkdiJcX+2w/7Xh7brTdtnGKACtmk9ALF+wHcMQqolqdew1iLC3EY4gbSh7cjI5tRRbwSFKUu6HEZzTjQBibfVxAu6krqXDMQEjilQCg95ofMeCN3XeCmdTRNsxVbHemgs7jSO6kxWK8lw9G/nP0B1qu/emmp7jBf3U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
